services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  nodejs:
    build:
      context: .
    container_name: truenavi
    ports:
      - "5000:5000" 
    environment:
      - MONGO_URI=mongodb://mongodb:27017/truenavi
    depends_on:
      - mongodb
    networks:
      - app-network
    command: "npm run start" 

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
